version: "3.1"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:8.0.19
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - datavol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "school_org"
      MYSQL_USER: "mainuser"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "securepassword"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: mainuser
      PMA_PASSWORD: password
    ports:
      - 127.0.0.1:8080:80
volumes:
  datavol: